### PR TITLE
Add support for maxInstances when creating a function

### PR DESCRIPTION
**Pull request by efiShtain**
### Description

This is a feature added to the public api to allow passing maxInstances property when creating or updating a firebase function.
This change requires a matching change on firebase-functions (there is another pull request for that)
https://github.com/firebase/firebase-functions/pull/624

### Scenarios Tested

No special testing is needed, as the parameter added is optional.
If you need to test it, create a function using firebase-functions and pass maxInstances parameter to RuntimeOptions. 
The function on google console will have the maxInstances parameter set correctly
It Cannot be viewed on the firebase console as far as I know

### Sample Commands

```javascript
import * as functions from 'firebase-functions'
functions
    .runWith({ maxInstances: 1 })
```

### CODE REVIEW

**Comment by efiShtain** [comment]
@googlebot I signed it!

**Comment by samtstern** [comment]
@efiShtain thanks for sending this!  Just a few things to know:

1. Please fill out the whole Pull Request template when sending a Pull Request so we know exactly what you're trying to do.
1. Any changes that affect the public API of a Firebase tool/SDK have to go through our internal API review process.  If we want to move forward with this change we'll handle that for you, but it will slow things down so just FYI.
1. I believe this PR would require a change in the `firebase-functions` library, right?

**Comment by efiShtain** [comment]
@samtstern 
Hey Sam,
Yeah that's the first time I commit a pull request for a google product

I'll see if I can fill in the rest of the details

There is a matching pull request on the firebase-functions too

Didn't know how to link them together, I also didn't change the package version as I didn't know what's the process regarding that too

**Comment by samtstern** [comment]
@efiShtain oh thanks!  I just saw your other PR:
https://github.com/firebase/firebase-functions/pull/624

So that one will have to be first, I'll get someone to take a look.

**Comment by samtstern** [comment]
@efiShtain a few scenarios you might want to test:

1. Try deploying a function without `maxInstances` and then deploying it again but with `maxInstances: 1` ... does that work as expected?
2. Try deploying a function once with `maxInstances: 1` and then again with `maxInstances: 2` ... does that work as expected?

Oh and don't worry about the version number, our release script does that automatically.

**Comment by efiShtain** [comment]
@samtstern 
I have checked for both cases before submitting the pull request and they work as expected

**Comment by joehan** [comment]
Hey @efiShtain, we just added this proposal to our 3/19 API review meeting. Thanks so much for working on this - I'll update here again after the meeting.

**Comment by joehan** [comment]
Wooo, this was approved! Thanks agin for working on this!

**Pull request merged**
