### PR TITLE
fixed #3426

### LINKED ISSUE #3426: function is not defined error after upgrading v9.6.1 to v9.12.0
### [REQUIRED] Environment info

**firebase-tools:** 9.12.0

**Platform:** linux

### [REQUIRED] Test case

`firebase functions:shell`

### [REQUIRED] Steps to reproduce
1. initialize the project with v9.6.1.
2. upgrade the firebase related packages to latest.
3. reinstall the packges (remove and install)
4. `firebase emulators:start`
5. `firebase functions:shell`

### [REQUIRED] Expected behavior
All http functions will should be callable in the shell.

### [REQUIRED] Actual behavior
But got this error
> Uncaught ReferenceError: functionName is not defined

### PR DESCRIPTION
**Pull request by syJSdev**
### Description

`trigger.id` and `trigger.name` are confused on `functionsShellCommandAction.ts`

### Scenarios Tested
joehan: Tested that  the following cases are defined from functions:shell
- A helloWorld HTTPS function in the default region - can be called as helloWorld()
- A helloWorld HTTPS function in multiple regions - defined once, as helloWorld()

### CODE REVIEW

**Comment by syJSdev** [comment]
@googlebot I signed it!

**Comment by samtstern** [comment]
@syJSdev thank you for the fix!

**Review by samtstern — APPROVED** [review]

**Comment by samtstern** [comment]
@syJSdev would you mind adding an entry to the `CHANGELOG` file describing this fix?

**Comment by joehan** [comment]
Thanks for this fix @syJSdev! We've got a patch release going out this morning, so I'll add an appropriate CHANGELOG entry and get this in

**Pull request merged**
