### PR TITLE
Use overall Functions lifecycle hook for individual function deploy

### PR DESCRIPTION
**Pull request by yzalvov**
In conclusion of the #1213, #1215 and #1216

### CODE REVIEW

**Comment by Memeriaj** [comment]
Woot! Everything has come together.

**Comment by yzalvov** [comment]
Great! So @Memeriaj do you want me to close #1213 and #1215 then?

**Comment by Memeriaj** [comment]
Yes please.

**Comment by Memeriaj** [comment]
Are you able to "Squash and merge" the PR?  Or do I need to do it?

**Comment by yzalvov** [comment]
I'm not sure. Part `Only those with write access to this repository can merge pull requests.` looks not promising. Here's the UI I have:

Screenshot 2019-04-25 at 01 13 14

**Comment by Memeriaj** [comment]
Okay, no sweat.  We typically do squash and merges because they tend to make the history cleaner (one commit on master per PR) but since this is just one commit and if I do a squash and merge it'll rewrite the commit to be mine, I'm just going to do a normal merge.

**Comment by yzalvov** [comment]
@Memeriaj many thanks for help. Please clarify, how long does it usually take to have a fix like this to be pushed to NPM so that `yarn upgrade` fixes the local version?

**Comment by Memeriaj** [comment]
On average we do a release every couple of days.  Depending on how busy I am this afternoon I'll try to do one myself.

**Pull request merged**
