### PR TITLE
Adding a smoke test for the data connect emulator

### PR DESCRIPTION
**Pull request by joehan**
### Description
Adding a simple smoke test for the data connect emulator. This will mainly catch wrong checksum/bytes. We'll add more meaningful tests later.

### Scenarios Tested
Confirmed that the test passes on the current HEAD. Then, editted downloadableEmulators.ts to have a bad checksum, and confirmed that the test fails.

### CODE REVIEW

**Review by maneesht — COMMENTED** [review]
I think this might be missing the script itself?

**Comment by joehan** [comment]
> I think this might be missing the script itself?

Yep, forgot to 'git add' 🤦 Fixed

**Review by maneesht — APPROVED** [review]
LGTM. Thanks for the change!

**Comment by joehan** [comment]
Windows tests are failing for no apparent reason, and I'm going slightly insane trying to debug them. Gonna submit running only on linux for now

**Pull request merged**
