### PR TITLE
typeRoots fix required on fresh install

### PR DESCRIPTION
**Pull request by ibnYusrat**
NPM tests are passing.
image

### Description
The fix mentioned here: https://github.com/firebase/firebase-functions/issues/551#issuecomment-561504411 is required even in a fresh install of `firebase init functions` and the option mentioned as the solution should be included in the `tsconfig.json` template by default.

I don't think its wise to make all new users visit this issue page to begin deploying functions. 

### Scenarios Tested
Details are in the above issue.

### Sample Commands
n/a

### CODE REVIEW

**Comment by samtstern** [comment]
@ibnYusrat thanks for sending a pull request!  Can you explain what fails without this fix?  I did a fresh `firebase init functions` using TypeScript and all the default choices and I was able to `npm run build` the standard function so I'm not sure what's broken.

**Comment by ibnYusrat** [comment]
> @ibnYusrat thanks for sending a pull request! Can you explain what fails without this fix? I did a fresh `firebase init functions` using TypeScript and all the default choices and I was able to `npm run build` the standard function so I'm not sure what's broken.
> 
> I was also able to `firebase deploy` without issue. Based on the issue you linked this has something to do with React? Can you show me how to get into the error state?

I am actually not even using react. My particular case was with using Angular. I did up date to the newest version of `firebase-tools` a few times today to run these tests, and I am not able to reproduce that issue. May be something else was interfering with the build. 

That being said, as you can see quite a few people were having this issue for over a year now (myself included), and all of them had to apply the same `typeRoots` fix to be able to deploy functions, and it seemed to be reasonable to include this by default so more people don't face the same problem. May be some more research needs to be done on why this keeps popping up for some of us.

**Comment by samtstern** [comment]
@ibnYusrat yeah I'm definitely concerned about how many people had that issue but I don't want to just apply this fix without understand what causes the problem and being sure that this is the best way to fix it.  

If you are able to reproduce it let me know.  If I have time I'll try again to get it to fail.

**Comment by ibnYusrat** [comment]
@samtstern Okay so here is an example of how it is breaking in my relatively simple project with only two functions in it. 

First, I removed the typeRoots fix, and then I added it again, you can see the error log in the gif. I will post my package.json if that could be of any help also. 

firebase_error

I can give you access to the project's repository also (privately) if that is required, of course that will not be possible in the public.

**Comment by samtstern** [comment]
@ibnYusrat private access would be very helpful!  My email is in my GitHub profile.

**Comment by ibnYusrat** [comment]
@samtstern Okay I sent you the invite to your email address. You should be able to clone the project now.

**Comment by ibnYusrat** [comment]
@samtstern Please note that the latest code would be in the `develop` branch, not the master branch.

**Comment by samtstern** [comment]
@ibnYusrat maybe I just don't know my way around GitLab but when i go to your repo I don't see any code or any way to switch branches.  Could you link me directly to a file?

**Comment by ibnYusrat** [comment]
@samtstern I just uploaded the repo to github, and invited you also. Please check if you have access. Thanks.

**Comment by samtstern** [comment]
@ibnYusrat got it thanks!

**Comment by ibnYusrat** [comment]
@samtstern Ok I think I found the culprit. To be able to recreate the issue, build a blank project (It was Angular in my case) and then install `"@testing-library/cypress": "^6.0.0",`. We don't generally use protractor and shifted to cypress a year ago. This is one of the dependencies that help with good testing practices.

If you install this dependency in any project, the `firebase deploy --only functions` will stop working. And I think quite a few people are using Cypress now a days for end to end testing.

**Comment by mbleigh** [comment]
This seems then like an issue with that specific dependency... perhaps they
can help figure out what's going on if you file an issue with them?

**Comment by ibnYusrat** [comment]
@mbleigh Yes, but that is only in my case. The other people who had similar issues (in the link above) don't seem to have `Cypress` in their dependencies at all (some of them posted their `package.json`s).  Which means there could be many other dependencies that have the same effect on `firebase deploy` and all of those are fixed with just typeRoots fix in `tsconfig.json`.

**Comment by samtstern** [comment]
@mbleigh do you think there's something here we want to adopt or should we close this?

**Comment by mbleigh** [comment]
I don't think we've seen enough reports of this to merit changing the defaults. Thanks for taking the time to submit a PR, but I think we'll wait for more feedback before doing something here.

**Comment by fandy** [comment]
I run into this with every new project that is already using TS. Imo this PR checks out since it's so easy to reproduce, and the Github issue mentioned seems to have a decent amount of reports judging by the emojis.

**Pull request closed without merging**
