### PR TITLE
Added typescript import plugin to eslintrc

### PR DESCRIPTION
**Pull request by awhitford**
As outlined from [Using eslint with typescript - Unable to resolve path to module](https://stackoverflow.com/a/56696478/195969), added the _typescript import plugin_ to avoid `Unable to resolve path to module` errors.

This impacted my firebase project that initially was setup with TSLint, but then I updated it, based on the latest templates, to migrate to ESLint.  There were 2 issues -- this one, and another issue that I can see has already been fixed.  This symptom is related to typescript code being in multiple files.

Note that I am using TypeScript 4, ESLint 7.10, and @typescript-eslint 4.4.0 (latest versions).

### CODE REVIEW

**Comment by samtstern** [comment]
@awhitford thank you for the PR!  Assigning to @bkendall who reviews All Things Lint :-)

**Comment by bkendall** [comment]
This makes sense to me - it's not _strictly_ necessary for the template we provide, but once you move to another file it's required, so it makes sense to be included.

Can you add this to the changelog?

```markdown
- Updates Cloud Functions for Firebase templates to better support function development.
```

Then update with master and this is good to go!

**Review by bkendall — CHANGES_REQUESTED** [review]
(see other comment about adding something to the changelog)

**Comment by awhitford** [comment]
@bkendall I made the requested changes.  (I feel like I need to mark this as resolved, but I don't see a button.  I see that "Merging is blocked / Merging can be performed automatically once the requested changes are addressed.") I guess I will leave this to you. Thank you for your review.

**Review by bkendall — APPROVED** [review]

**Comment by bkendall** [comment]
Thanks!

**Pull request merged**
