### PR TITLE
Expose per-emulator options in the serve command

### PR DESCRIPTION
**Pull request by ryanpbrewster**

### CODE REVIEW

**Comment by laurenzlong** [comment]
The build is broken.

**Comment by ChromeQ** [comment]
Why was this PR deleted? I thought it was a really nice feature since sometimes my port 8080 is used up in another project and this is causing a conflict. Would be nice to specify different ports for the functions & firestore & hosting emulators

**Comment by samtstern** [comment]
If you're using "emulators:start" you can specify the ports in your
firebase.json file:

{
  "emulators": {
    "firestore": { "port": 1234 }
  }
}

**Comment by semla** [comment]
it would be convenient to be able to override the firebase.json via the command-line

**Pull request closed without merging**
