### PR TITLE
Use relative redirect URLs for resumable storage uploads.

### PR DESCRIPTION
**Pull request by yuchenshi**
### Description

Fixes https://github.com/firebase/firebase-admin-node/issues/1562

### Scenarios Tested

See tests enabled.

### Sample Commands

N/A

### CODE REVIEW

**Comment by yuchenshi** [comment]
Actually this breaks on CI with `Only absolute URLs are supported`. Will investigate and may drastically change my approach. Converting to draft now

**Comment by bkendall** [comment]
> Actually this breaks on CI with `Only absolute URLs are supported`. Will investigate and may drastically change my approach. Converting to draft now

yay integration test? I think they're _absolutely_ necessary in cases like this

**Comment by vajahath** [comment]
Please let me know if I can do something here to support. If this PR is already in pipeline, all good. :+1:

**Comment by yuchenshi** [comment]
Closing in favor of #4409

**Comment by yuchenshi** [comment]
Closing in favor of #4409

**Pull request closed without merging**
