### PR TITLE
Add what type of token is returned

### PR DESCRIPTION
**Pull request by ersin-ertan**

### CODE REVIEW

**Comment by bkendall** [comment]
Thank you for the PR! At a quick glance, I think this is pretty good. As a suggestion (and as a bit of more information for me since you left the description empty): can you provide in the markdown a link to the Google OAuth2 documentation - or better yet, the Firebase documentation - that talks about this token that is returned? Surely this information can be found elsewhere, and having a link right in context to learn more would be great!

Include it just as a markdown link, so:

```markdown
something something [Google OAuth2](https://example.com) other stuff.
```

Thanks!

**Comment by ersin-ertan** [comment]
Thanks for the guidance Bryan. I've linked to Google's Oauth2 Cloud Identity Overview page, and am debating if the link to Firebase Authentication is needed because it includes a sentence describing what you can use the token for "You can also use the provided authentication token to verify the identity of users in your own backend services."

**Comment by bkendall** [comment]
I don't think you want to include a link to Firebase Auth in this particular PR. Since this is just dealing with the tokens to run Firebase commands against our servers rather than authenticate an applications _users_ through Firebase, the Google OAuth docs are the correct source, I believe.

Thanks for taking this on!

**Comment by bkendall** [comment]
I'm going to want @mbleigh 's take on this quickly before we merge it, but I think this should be fine. It will probably be next week when we come back to this. Thanks

**Comment by bkendall** [comment]
Alright, this has been merged (though, I did it manually so you'd still get credit for it!)

Thanks for the PR!

**Pull request closed without merging**
