### PR TITLE
auth:export - Ensure all fetched and transformed data is written to file before exit

### PR DESCRIPTION
**Pull request by jpreynat**
### Description

Fix remaining issue #1635 after #1636.
Basically, since the `serialExportUsers` method is now returning early if now token was returned from the Google API, the data written to the output file `WriteStream` for the last request does not have enough time to be flushed before the command ends.
This PR makes sure that it is the case.

### CODE REVIEW

**Comment by jpreynat** [comment]
Done @bkendall

**Comment by samtstern** [comment]
@bkendall's changes have been done, so I am going to merge.  Thank you to @jpreynat for doing this!

**Comment by bkendall** [comment]
👍 thanks!

**Comment by jpreynat** [comment]
You’re most welcome.
Sorry for the previous broken update and thanks for merging this one 👍

**Comment by Rigter** [comment]
If someone still experiencing problems after update to `7.3.1` just run:
```
firebase login --reauth
```
Then, try the `firebase auth:export` command again ✌🏻

```
firebase auth:export FILENAME.json -P PROJECT_ID
```

**Comment by benwinding** [comment]
@Rigter that didn't fix it for me

Just upgrading to the latest firebase tools worked for me:

`npm i -g firebase-tools`

**Comment by akashgangrade** [comment]
I have updated firebase-tools to 7.6.1 version, but still facing the issue.
Tried _firebase login --reauth_  also, but it didn't work for me.

**Comment by bkendall** [comment]
@akashgangrade please open a new issue with the appropriate information if you are still having troubles... thanks!

**Pull request merged**
