### PR TITLE
Update text for SDK Configuration button

### PR DESCRIPTION
**Pull request by hlshen**
Screenshot 2024-10-07 at 1 38 47 PM

### CODE REVIEW

**Comment by fredzqm** [comment]
What do folks think of "Add SDK to my app"?

**Review by yuchenshi — APPROVED** [review]
I'm okay with whatever wording

**Comment by fredzqm** [comment]
https://github.com/search?q=repo%3Afirebase%2Ffirebase-tools+%22Configure+Generated+SDK%22&type=code

Do we want to update the code lens name as well?

**Comment by hlshen** [comment]
I'm a bit indecisive. I feel that once you're in the yaml file, it makes sense to think of configuring settings. Thus "Configure Generated SDK" makes more sense.

**Review by joehan — APPROVED** [review]

**Comment by fredzqm** [comment]
> I'm a bit indecisive. I feel that once you're in the yaml file, it makes sense to think of configuring settings. Thus "Configure Generated SDK" makes more sense. 

"Configure Generated SDK" makes sense to us, but not really for developers.

On the connector.yaml, maybe "Use Connector in the app".

Can come later. I think js and kotlin would work fine, but iOS needs additional steps.
CLI displays those messages. VS Code should do the same or we actually figure out how to import it in the app properly.

**Pull request merged**
