### PR TITLE
Unlock the Emulator UI

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Removes the GUI from previews and also makes it have real versions/caching.

### Scenarios Tested

Two back-to-back runs:

```
$ firebase emulators:start
i  emulators: Starting emulators: functions, firestore, database
✔  hub: emulator hub started at http://localhost:4400
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: functions emulator started at http://localhost:5001
i  firestore: firestore emulator logging to firestore-debug.log
✔  firestore: firestore emulator started at http://localhost:8090
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8090
⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file. The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  database: database emulator logging to database-debug.log
✔  database: database emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting?
✔  logging: logging emulator started at http://localhost:4500
i  gui: downloading gui-v0.0.1-EAP.zip...
Progress: ==========================> (100% of 4MB
i  gui: Removing outdated emulator files: gui-v0.0.0-EAP
i  gui: Removing outdated emulator files: gui-v0.0.0-EAP.zip
i  gui: emulator GUI logging to gui-debug.log
✔  gui: emulator GUI started at http://localhost:4000
i  functions: Watching "/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.S2rWicGj/functions" for Cloud Functions...
✔  functions[helloWorld]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/helloWorld).
✔  emulators: All emulators started, it is now safe to connect.
^Ci  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  gui: Stopping emulator GUI
⚠  emulator GUI has exited upon receiving signal: SIGINT
i  logging: Stopping logging emulator
i  functions: Stopping functions emulator
i  firestore: Stopping firestore emulator
i  database: Stopping database emulator
```

```
$ firebase emulators:start
i  emulators: Starting emulators: functions, firestore, database
✔  hub: emulator hub started at http://localhost:4400
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: functions emulator started at http://localhost:5001
i  firestore: firestore emulator logging to firestore-debug.log
✔  firestore: firestore emulator started at http://localhost:8090
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8090
⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file. The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  database: database emulator logging to database-debug.log
✔  database: database emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting?
✔  logging: logging emulator started at http://localhost:4500
i  gui: emulator GUI logging to gui-debug.log
✔  gui: emulator GUI started at http://localhost:4000
i  functions: Watching "/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.S2rWicGj/functions" for Cloud Functions...
✔  functions[helloWorld]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/helloWorld).
✔  emulators: All emulators started, it is now safe to connect.
^Ci  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  gui: Stopping emulator GUI
⚠  emulator GUI has exited upon receiving signal: SIGINT
i  logging: Stopping logging emulator
i  functions: Stopping functions emulator
i  firestore: Stopping firestore emulator
i  database: Stopping database emulator
```

### CODE REVIEW

**Comment by samtstern** [comment]
@yuchenshi I was thinking we do this in two parts:

1) Merge this 
2) A follow up PR to specify the real ZIP path / size / checksum for the v0 release

**Comment by yuchenshi** [comment]
I'd suggest actually just amend this PR to include the real path / size / checksum once we're ready. I'd like as few middle states as possible especially given the caching issues. Would you mind converting this to a draft? I'll approve once we have the correct literals.

**Comment by samtstern** [comment]
@yuchenshi SGTM

**Comment by yuchenshi** [comment]
DO_NOT_MERGE=waiting for launch

**Pull request merged**
