### PR TITLE
Update ALLOWED_SSR_REGIONS constant for web frameworks

### PR DESCRIPTION
**Pull request by jamesxabregas**
### Description
Update list of `ALLOWED_SSR_REGIONS` in web frameworks config to include the current list of regions that support gen 2 Cloud Functions.

#5504 added the ability to select an SSR region other than 'us-central1', but it was limited to regions that supported Gen 2 Cloud Functions at the time which has since expanded. This change updates the list of supported regions.

### Scenarios Tested

Tested deploying to new regions using config in `firebase.json`

```
frameworksBackend": {
      "region": "australia-southeast1"
}
```

### Sample Commands

Commands have not changed.

As per previous functionality, run:

```
firebase experiments:enable webframeworks
firebase init hosrting
firebase deploy
```

### CODE REVIEW

**Comment by alexastrum** [comment]
Sorry for the delay. LGTM

**Review by alexastrum — APPROVED** [review]

**Comment by jamesxabregas** [comment]
Hi maintainers, just wondering if there is something in particular I need to do to get this change merged? 
It was approved 3 weeks ago but still waiting to be merged.

**Comment by al4nnw** [comment]
@alexastrum My project is starting to generate some fees related to intercontinental network egress.

V2 functions are already supported in a lot of regions.

Could we get this approved?

**Comment by jamesxabregas** [comment]
@alexastrum could you please merge these changes, or tell me what needs to be done to progress this. Thank you.

**Comment by eXodes** [comment]
@jamesxabregas It seems that the fork `master` is outdated. Could you please help merge the latest `firebase-tools`?

**Comment by jamesxabregas** [comment]
> @jamesxabregas It seems that the fork `master` is outdated. Could you please help merge the latest `firebase-tools`?

@eXodes I updated `master` in my fork. Now what?

**Comment by eXodes** [comment]
Paging @alexastrum for approval.

**Comment by jamesdaniels** [comment]
Closing in favor of #6591

**Pull request closed without merging**
