### PR TITLE
Include admin & initialization in functions init

### PR DESCRIPTION
**Pull request by jamesdaniels**
Since this is such a common pattern, I figured we should include it in the initialization even if it's not required for the commented out helloWorld example. Thoughts @mbleigh ?

### CODE REVIEW

**Comment by jamesdaniels** [comment]
Yeah I'd be just as happy if they were commented out.

**Comment by inlined** [comment]
If we had a (commented out) example that uses the SDK then this would be a no-brainer and two wins.

**Comment by laurenzlong** [comment]
@mbleigh @jamesdaniels This PR has been sitting here for a while, how do we want to move forward?

**Comment by inlined** [comment]
This should be abandoned for a few reasons:

1. Eventually Firebase Admin should only be required when developers are actually using Firebase.
2. Firebase Admin can only be initialized once and this will break thousands of existing customers.
3. Initializing Firebase Admin with default credentials prevents developers from initializing (the default instance of) Firebase Admin with a certificate file. Certificate files are still necessary for minting Firebase Auth tokens and creating download/upload URLs in Cloud Storage.

**Pull request closed without merging**
