### PR TITLE
Delete changelog.txt

### PR DESCRIPTION
**Pull request by SUPERCILEX**
It's an empty file.

### CODE REVIEW

**Comment by laurenzlong** [comment]
Thanks for the contribution! This file is actually important for our release system, it gets populated with release notes prior to every new release (e.g. https://github.com/firebase/firebase-tools/pull/602), and reset to empty automatically after the release.

**Comment by laurenzlong** [comment]
This is where the release notes end up: https://github.com/firebase/firebase-tools/releases

**Comment by SUPERCILEX** [comment]
@laurenzlong Oh, got it! Maybe it could contain a "Do not remove" message or something instead of being blank?

**Comment by laurenzlong** [comment]
No worries. Many Firebase repositories rely on the same release system, so I'm hesitant to change things without there being a very good reason.

**Comment by SUPERCILEX** [comment]
Alrighty, SGTM! 😊

**Pull request closed without merging**
