### PR TITLE
Add Dependabot

### PR DESCRIPTION
**Pull request by aravindvnair99**
Dependabot creates pull requests to keep your dependencies secure and up-to-date.

Refer: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically

### CODE REVIEW

**Comment by samtstern** [comment]
@aravindvnair99 thanks for the heads up! I just enabled dependabot in our repo settings (not sure why it was off) so I don't think we'll need this file. But we appreciate the contribution and reminder

Screen Shot 2021-05-18 at 11 50 55 AM

**Comment by aravindvnair99** [comment]
@samtstern The configuration file is necessary so that Dependabot knows which environments to update. My commit is basically the most minimal config to update npm dependencies. You can read more about the configuration options here: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#configuration-options-for-updates

**Comment by samtstern** [comment]
@aravind I think GitHub is actually smart enough to figure it out without that file, you can see here that dependabot sent this PR just seconds after I enabled it:
https://github.com/firebase/firebase-tools/pull/3383

**Comment by aravindvnair99** [comment]
@samtstern Hmmm true, I'm not sure why GitHub mandates the config file though. I'll get back to you in case I find anything else.

**Comment by aravindvnair99** [comment]
Hey @samtstern!

Just thought I'll let you know that I got it clarified by a GitHub staff here: https://github.com/dependabot/dependabot-core/issues/3743.

TLDR: Adding config file runs on schedule to send PRs with updated dependencies and the 2 options in repository settings are only for known vulnerabilities.

**Comment by samtstern** [comment]
That's great thanks for checking! Since we don't want to use version updates we can do without the file for now. 

Also that wasn't just any GitHub employee you found, that was @asciimike who worked on Firebase almost from the beginning!

**Comment by aravindvnair99** [comment]
Oh wow @samtstern! I didn't know that, but I do recognise @asciimike from a couple of Firebase videos I watched in the past when I was first exploring Firebase back in 2017 / 2018. I think I have seen him on other conferences as well if I remember correctly.

But yeah, I just looked him up on [LinkedIn](https://www.linkedin.com/in/asciimike/) after you mentioned.

**Pull request closed without merging**
