### PR TITLE
upgrade commander; update command help formatting

### PR DESCRIPTION
**Pull request by bkendall**
### Description

when using custom help `Command.help()`, the help text was smashed right against the list of options. This additional line print gives it space.

Updating `Commander` as well. [Changelog for commander](https://github.com/tj/commander.js/blob/master/CHANGELOG.md#500-2020-03-14)

edit: fixed the link

### CODE REVIEW

**Comment by samtstern** [comment]
@bkendall funny changelog link you got there...

**Comment by bkendall** [comment]
Fixed the link.

**Comment by samtstern** [comment]
@bkendall there are many breaking changes about options and arg parsing in there, none of them affect us?

**Comment by samtstern** [comment]
@bkendall still want to pursue this one?

**Comment by bkendall** [comment]
Yes, we probably should, but I'm not going to worry about it right now. Migrating is actually a bit of a headache because of the new "preventing collisions with Commander properties" logic they added.

**Pull request closed without merging**
