### PR TITLE
Update changelog to V.3.2.3

### PR DESCRIPTION
**Pull request by laurenzlong**

### CODE REVIEW

**Comment by wyhao31** [comment]
You should replace lastLoginAt with lastSignedInAt. lastSignedInAt is the public field name.

**Comment by wyhao31** [comment]
I think you can also mention PBKDF2_SHA256 support and Fix issues with SCRYPT.

**Comment by laurenzlong** [comment]
Thanks @wyhao31 ! Made the changes you suggested.

**Comment by mbleigh** [comment]
`changed` is meant for breaking changes. For the purposes of this release I think these are all probably `fixed` entries (if they're not, we'd need to do a minor version bump).

I'd probably collapse the whole changelog into a single line like:

    fixed - Improvements to `auth:import`: support for `lastSignedInAt` and `createdAt` fields, no hash algo required for non-password users, support for `PBKDF2_SHA256` algorithm.

**Pull request merged**
