### PR TITLE
Release database emulator v4.2.0

### PR DESCRIPTION
**Pull request by IanWyszynski**
Database emulator release for function triggers upsert endpoint.

### CODE REVIEW

**Comment by samtstern** [comment]
```
$ npx firebase emulators:start
i  Starting emulators: ["functions","database"]
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5001
i  database: downloading firebase-database-emulator-v4.2.0.jar...
Progress: ===================================================================> (100% of 18MB)
i  Shutting down emulators.
i  Stopping functions emulator

Error: download failed, expected 17131418 bytes but got 17124145
```

**Comment by IanWyszynski** [comment]
> ```
> $ npx firebase emulators:start
> i  Starting emulators: ["functions","database"]
> ⚠  Your requested "node" version "8" doesn't match your global version "10"
> ✔  functions: Emulator started at http://localhost:5001
> i  database: downloading firebase-database-emulator-v4.2.0.jar...
> Progress: ===================================================================> (100% of 18MB)
> i  Shutting down emulators.
> i  Stopping functions emulator
> 
> Error: download failed, expected 17131418 bytes but got 17124145
> ```

Forgot to update the storage url.

**Comment by IanWyszynski** [comment]
> > ```
> > $ npx firebase emulators:start
> > i  Starting emulators: ["functions","database"]
> > ⚠  Your requested "node" version "8" doesn't match your global version "10"
> > ✔  functions: Emulator started at http://localhost:5001
> > i  database: downloading firebase-database-emulator-v4.2.0.jar...
> > Progress: ===================================================================> (100% of 18MB)
> > i  Shutting down emulators.
> > i  Stopping functions emulator
> > 
> > Error: download failed, expected 17131418 bytes but got 17124145
> > ```
> 
> Forgot to update the storage url.

```
i  Starting emulators: ["database"]
i  database: downloading firebase-database-emulator-v4.2.0.jar...
Progress: =====================================================================================================================================> (100% of 18MB)
i  database: Removing outdated emulator: firebase-database-emulator-v4.1.1.jar
i  database: Emulator logging to database-debug.log
✔  database: Emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
✔  All emulators started, it is now safe to connect.
```

**Comment by samtstern** [comment]
Modified the functions emulator to use the new endpoint, then tested with these functions:
```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.helloWorld = functions.https.onRequest(async (request, response) => {
 
    await admin.database().ref('test/test1').set({ hello: 'world '});
    await admin.database().ref('test/test2').set({ hello: 'other' });

    response.send("Hello from Firebase!");
});

exports.databaseOne = functions.database.ref('test/test1').onWrite((change, ctx) => {
    console.log('DB1');
    return true;
});

exports.databaseTwo = functions.database.ref('test/test2').onWrite((change, ctx) => {
    console.log('DB2');
    return true;
});
```

Got this result:
```bash
$ npx firebase emulators:start
i  Starting emulators: ["functions","database"]
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5001
i  database: Emulator logging to database-debug.log
✔  database: Emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
i  functions: Watching "/tmp/tmp.ddVISM2wPN/functions" for Cloud Functions...
✔  functions[helloWorld]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/helloWorld).
✔  functions[databaseOne]: database function initialized.
✔  functions[databaseTwo]: database function initialized.
✔  All emulators started, it is now safe to connect.
i  functions: Beginning execution of "helloWorld"
i  functions: Finished "helloWorld" in ~1s
i  functions: Beginning execution of "databaseTwo"
i  functions: Beginning execution of "databaseOne"
>  DB1
i  functions: Finished "databaseOne" in ~1s
>  DB2
i  functions: Finished "databaseTwo" in ~1s
```

**Comment by bkendall** [comment]
You'll want to sync your branch w/ `master` locally on your machine. `changelog.txt` has been renamed to `CHANGELOG.md`, so your entry will just have to be moved.

**Pull request merged**
