### PR TITLE
Issue 1759 export users #1762

### PR DESCRIPTION
**Pull request by akashgangrade**
#1759 Handled condition for connect ETIMEDOUT error and called serialExportUsers function again with last nextPagetoken

### Description
On exporting user data from firebase auth export command after few iterations, the export command throws connection timed-out(ETIMEDOUT) error and the script gets terminated. 
This was happening due to timeout from "https://www.googleapis.com/identitytoolkit/v3/relyingparty/downloadAccount"  API and this condition was not handled in code(no catch block was present in code to handle this timeout condition).
I have added a catch block and checked for specific ETIMEDOUT code, if that error code encountered in catch block then I have called the function "serialExportUsers" again with the same project Id and options params.
This solved the problem of ETIMEDOUT, now the script is working fine and able to fetch all the records.

### CODE REVIEW

**Comment by samtstern** [comment]
@akashgangrade thanks for this pull request.  Is there a reason you closed #1762 and opened this one?

**Comment by akashgangrade** [comment]
@samtstern : Actually I signed CLA for that pull request but the status _cla:no_ was not getting updated. That's why I have created new pull request.

**Comment by bkendall** [comment]
Thank you for the PR! 😄

**Comment by akashgangrade** [comment]
> Thank you for the PR! 😄

Thank you for accepting PR :)

**Pull request merged**
