### PR TITLE
Fix clean build

### PR DESCRIPTION
**Pull request by samtstern**
### Description

While investigating #2383 I did `rm -rf package-lock.json node_modules` and then ran into a *lot* of errors on trying to run `npm install` again.  With these changes I can now build again.

### Scenarios Tested

```
rm -rf package-lock.json node_modules
npm install
```

### Sample Commands

N/A

### CODE REVIEW

**Comment by samtstern** [comment]
@bkendall I'm not really sure if deleting `package-lock.json` and regenerating is appropriate ... but at some level these are real issues.

Open to ideas.

**Comment by bkendall** [comment]
so what this means it that (functionally) you are upgrading all the packages to the latest version that can be supported by `package.json` (every time you remove `node_modules` and `package-lock.json`). while somewhat useful, this probably isn't the desired behavior you're looking for (as this requires a lot of code changes as things subtly change). If you're looking to control the dependencies as they are installed everywhere (like how `package-lock.json` keeps all developers on the same dependencies), we should look into [shrinkwrap](https://docs.npmjs.com/files/shrinkwrap.json) (which I have mentioned before and never really have gathered enough interest or support).

Right now, if we have a shrinkwrap that could keep the bad winston out of our codebase, we wouldn't have the problem everyone else is having (and this is I think the 3rd time in ~1-2 years that this has happened).

**Comment by bkendall** [comment]
To this PR, I think you could do it, but all the tests and errors will have to be taken care of (and I bet this updated a bunch of rules for the linter too)

**Comment by samtstern** [comment]
@bkendall ok yeah that all makes sense.  What if instead of `shrinkwrap` we just actually pinned our dependencies to specific versions?  We could use something like Renovate to try and keep them up to date but the whole floating version thing in general seems like junk to me (coming from a bacgkround in Android where that's bad practice).

**Comment by bkendall** [comment]
I think it's much easier to use `shrinkwrap` than it is to enforce that
dependencies are pinned and to add a new tool to manage it. I think that if
we use `shrinkwrap`, we can also take the step to use Renovate (or another
dependency manager) to keep things as up to date as possible. The biggest
argument in allowing the 'floating version thing' to continue as-is is that
users automatically get any security patches of dependencies.
Unfortunately, as the world has shown, sometimes a version update breaks
things rather dramatically.

Does Renovate work with `shrinkwrap`? I used to use greenkeeper which has
been absorbed by [sync](snyk.io). Another that is used a LOT is [lerna](
https://lerna.js.org/) - that's very useful in a multi-package repository,
but it may have some nice automation we could use to keep things up to date.

**Comment by samtstern** [comment]
Closing this, although whenever we do update things this will be a useful reference about our `inquirer` usage.

**Pull request closed without merging**
