### PR TITLE
Have the console print a newline character at the end of firestore:de…

### PR DESCRIPTION
**Pull request by DCtheTall**
### Description

Have the console start the next command after `firestore:delete` on a new line.

Fixes issue [#1737](https://github.com/firebase/firebase-tools/issues/1737).
	 
### Scenarios Tested

- Running `firestore:delete` successfully and at least one document is deleted.
- Running `firestore:delete` successfully and no documents are deleted.

I couldn't get all of the error codepaths to execute, but if anyone has suggestions I am open to testing those as well.

### Sample Commands

Run `firestore:delete` on a document or collection with one or more documents and the console will start the next command on a new line.

### CODE REVIEW

**Comment by samtstern** [comment]
@DCtheTall would it work if you put a newline directly into the `ProgressBar`:
```js
new ProgressBar("Deleted :current docs (:rate docs/s)\n" // <-- newline added
```

**Comment by DCtheTall** [comment]
@samstern yea that is a simpler approach. Done.

**Comment by samtstern** [comment]
@DCtheTall cool!  Once the build passes I will merge.

**Comment by DCtheTall** [comment]
@samtstern

**Pull request merged**
