### PR TITLE
Fix yml file writes in firebase init hosting:github

### PR DESCRIPTION
**Pull request by jhuleatt**
### Description

Fixes bugs in the `firebase hosting init:github command` where:
- The `firebase-hosting-pull-request.yml` file was written to the wrong location even though the CLI logged the correct location
- The `firebase-hosting-merge.yml` file was never written

### Scenarios Tested

- `firebase init hosting:github`, answered "no" to "Set up automatic deployment to your site's live channel when a PR is merged?"
- `firebase init hosting:github`, answered "yes" to "Set up automatic deployment to your site's live channel when a PR is merged?"

```
>firebase init hosting:github 
// ...
=== Hosting:github Setup

i  Detected a .git folder at /Users/jhuleatt/git/how-cool-is-this
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
<REDACTED/>

Waiting for authentication...

✔  Success! Logged into GitHub as jhuleatt

? For which GitHub repository would you like to set up a GitHub workflow? jhuleatt/super-duper-happiness

✔  Created service account <REDACTED/> with Firebase Hosting admin permissions.
✔  Uploaded service account JSON to GitHub as secret FIREBASE_SERVICE_ACCOUNT_ACTION_HOSTING_DEPLOY_DEMO.
i  You can manage your secrets at <REDACTED/>.

? Set up the workflow to run a build script before every deploy? Yes
? What script should be run before every deploy? npm ci && npm run build

✔  Created workflow file /Users/jhuleatt/git/how-cool-is-this/.github/workflows/firebase-hosting-pull-request.yml
? Set up automatic deployment to your site's live channel when a PR is merged? Yes
? What is the name of the GitHub branch associated with your site's live channel? master

✔  Created workflow file /Users/jhuleatt/git/how-cool-is-this/.github/workflows/firebase-hosting-merge.yml

i  Action required: Visit this URL to revoke authorization for the Firebase CLI GitHub OAuth App:
<REDACTED/>
i  Action required: Push any new workflow file(s) to your repo

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```

### CODE REVIEW

**Review by henrypbriffel — APPROVED** [review]
Where A&Tsync

**Review by mbleigh — APPROVED** [review]
Add a `CHANGELOG.md` please?

**Comment by jhuleatt** [comment]
Added `CHANGELOG.md` entry - I think I added it in the right spot?

**Comment by mbleigh** [comment]
yup, lgtm

**Pull request merged**
