### PR TITLE
Depend on mime directly

### LINKED ISSUE #3254: mime is missing from dependencies, breaking Yarn Plug'n'Play
This is similar to #2974. The following code: https://github.com/firebase/firebase-tools/blob/3014db6ee1c839b76675823ef13119f4ef487a6b/src/emulator/storage/apis/firebase.ts#L5 depends on the package `mime`, but `package.json` file does not declare dependency on it. This makes it hard to use `firebase-tools` with Yarn 2 Plug'n'Play. See https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies for details of the restrictions Yarn 2 Plug'n'Play puts.

### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** Ubuntu

### [REQUIRED] Test case

See “Steps to reproduce” below.

### [REQUIRED] Steps to reproduce

Set up Yarn 2 with the default settings, which enable Plug'n'Play:

```
$ mkdir firebase-testcase
$ cd firebase-testcase
$ cat > package.json
{
  "name": "firebase-testcase",
  "private": true
}
^D
$ yarn set version berry
```

Install firebase-tools:

```
$ yarn add -D firebase-tools
```

Run the firebase CLI:

```
$ yarn firebase
```

### [REQUIRED] Expected behavior

The firebase CLI runs.

### [REQUIRED] Actual behavior

```
$ yarn firebase
/tmp/firebase-testcase/.pnp.js:11350
    throw firstError;
    ^

Error: firebase-tools tried to access mime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: mime (via "mime")
Required by: firebase-tools@npm:9.8.0 (via /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/apis/)

Require stack:
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/server.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/index.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/controller.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/commandUtils.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/commands/database-get.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/commands/index.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/index.js
- /tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/bin/firebase.js
    at internalTools_makeError (/tmp/firebase-testcase/.pnp.js:11094:34)
    at resolveToUnqualified (/tmp/firebase-testcase/.pnp.js:12059:23)
    at resolveRequest (/tmp/firebase-testcase/.pnp.js:12151:29)
    at Object.resolveRequest (/tmp/firebase-testcase/.pnp.js:12229:26)
    at Function.external_module_.Module._resolveFilename (/tmp/firebase-testcase/.pnp.js:11327:34)
    at Function.external_module_.Module._load (/tmp/firebase-testcase/.pnp.js:11192:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/tmp/firebase-testcase/.pnp.js:11223:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/firebase-testcase/.yarn/cache/firebase-tools-npm-9.8.0-8477e88a6d-b96f523008.zip/node_modules/firebase-tools/lib/emulator/storage/server.js:9:20)
```

### PR DESCRIPTION
**Pull request by ti1024**
### Description

Bug fix: Depend on mime directly so that firebase-tools works correctly with Yarn Plug'n'Play (https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies).

Closes #3254.

### CODE REVIEW

**Comment by samtstern** [comment]
@ti1024 thanks for this PR!  It looks like we use `mime` in the Storage emulator. And here's how we get it in our tree:

```
firebase-tools@9.8.0 /Users/samstern/Projects/firebase-tools
├─┬ express@4.17.1
│ └─┬ send@0.17.1
│   └── mime@1.6.0 
├─┬ firebase-admin@9.4.2
│ └─┬ @google-cloud/storage@5.7.0
│   └── mime@2.4.6 
├─┬ google-auth-library@6.1.3
│ └─┬ gtoken@5.1.0
│   └── mime@2.4.6 
└─┬ supertest@3.4.2
  └─┬ superagent@3.8.3
    └── mime@1.6.0  deduped
```

The only place we actually use it is:
```
const mimeTypeFromName = mime.getType(name);
```

From the release notes here:
https://github.com/broofa/mime#version-2-notes

It appears that `getType()` is actually a 2.x function whereas it was called `lookup()` in 1.x ... so can you update this PR to make the dependency a `mime` 2.0 version or higher?

**Comment by ti1024** [comment]
I agree that the code depends on mime v2. Thanks for catching it.

However, I encountered a problem. When I ran `npm install --save mime` (from the clean source), it added `{"mime", "^2.5.2"}` to `dependencies` in package.json (as expected), but it did not update package-lock.json (not expected). This caused the tests (the `npm ci` step) to fail (expected given that package.json and package-lock.json are conflicting).

I tried random stuff like:

* ran `npm update mime`
* removed the mime 1.6.0 entry from package-lock.json and ran `npm install --save mime`

but neither updated package-lock.json.

Should I do anything special to update package-lock.json? I am using npm 6.14.12 on Ubuntu.

**Comment by ti1024** [comment]
FWIW, I _think_ that this PR also fixes an actual bug in Storage Emulator (it tries to use the API of mime v2 but I think it uses mime v1 with the package-lock.json file before this PR). But I have not used Storage Emulator yet and I cannot confirm the bug.

**Comment by samtstern** [comment]
@ti1024 thank you for this!  Looks great.

**Review by samtstern — APPROVED** [review]

**Comment by bkendall** [comment]
@ti1024 thanks again for this fix! It's really appreciated :)

**Pull request merged**
