### PR TITLE
Don't iterate randomly on auth:export command

### LINKED ISSUE #1635: auth:export command returns duplicate results
### [REQUIRED] Environment info

**firebase-tools:** 7.3.0 and earlier

**Platform:** macOS

### [REQUIRED] Test case

```bash
$ firebase-tools auth:export auth.json

# Log number of accounts in the file (found by their `localId` property)
$ cat auth.json | grep localId | wc -l
3949724

# Log actual number of de-duplicated accounts in the file
$ cat auth.json | grep localId | sort | uniq | wc -l
367793
```

Our Firebase Auth counts more than 300000 accounts. We export them using the `auth:export` command regularly to analyze them.
Until recently, it worked great. But as you can see above, today the export file includes 10x more accounts than their actual number. The number of de-duplicated accounts matches the number of accounts displayed in our Firebase Auth dashboard, so we are sure that this is the correct one.

After a short investigation, it seems that the Google API that `firebase-tools` relies on to list the accounts `/identitytoolkit/v3/relyingparty/downloadAccount` has changed its behavior and returns a [`nextPageToken`](https://github.com/firebase/firebase-tools/blob/master/src/accountExporter.js#L161) randomly now when the end of the users list is reached.

Here are some logs of an homemade module that uses this API and logs the `nextPageToken` value after each completion call:
```
nextPageToken undefined
Exported 773 users, total: 0
nextPageToken undefined
Exported 773 users, total: 773
nextPageToken undefined
Exported 773 users, total: 1546
nextPageToken undefined
Exported 773 users, total: 2319
nextPageToken undefined
Exported 773 users, total: 3092
nextPageToken undefined
Exported 773 users, total: 3865
nextPageToken undefined
Exported 773 users, total: 4638
nextPageToken undefined
Exported 773 users, total: 5411
nextPageToken visitor_uid
Exported 773 users, total: 6184
nextPageToken undefined
Finished with 6957
```

You can see that at some point, `nextPageToken` is `visitor_uid`, which ends the loop, while it returns `undefined` most of the time.

Given the code of the `auth:export` function, it's logic that the command currently loops, potentially endlessly.
We should add a check [here](https://github.com/firebase/firebase-tools/blob/master/src/accountExporter.js#L161-L162) to ensure that `nextPageToken` has actually been returned with a value before iterating again.

@mbleigh Could you also check the reason of this update on the Google API? Maybe it's just a temporary bug, but since the API is deprecated, it's not possible to check for its current status.

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

The file should include only the correct number of accounts from Firebase Auth.

### [REQUIRED] Actual behavior

The file includes duplicates of the accounts, and `firebase-tools` can potentially iterate endlessly on calling the `identitytoolkit` endpoint.

### PR DESCRIPTION
**Pull request by jpreynat**
### Description

Fixes #1635 
	 
### Scenarios Tested

Tested locally.

```bash
$ cat auth.json | grep localId | wc -l
  367001

$ cat auth.json | grep localId | sort | uniq | wc -l
  367001
```

### CODE REVIEW

**Comment by samtstern** [comment]
@jpreynat based on the API docs this seems correct:
https://developers.google.com/identity/toolkit/web/reference/relyingparty/downloadAccount

Let me just see if @bojeil-google has any thoughts before merging.

**Comment by bkendall** [comment]
(seems like a good thing to note in the changelog?)

**Comment by AaronO** [comment]
It would be great to get this merged and released, since `auth:export` is broken in it's current state.

Do you have an ETA of when this would be merged & releasesd ?

**Comment by samtstern** [comment]
Ah we solved the mystery!  According to @bojeil-google the backend recently made a change to (correctly) not return a `nextPageToken` when the next page is empty.  What used to happen is that the backend would return a token pointing at an empty page, which would hit the `users.length > 0` condition and get us out of the loop.

So now we correctly handle the lack of a token.

**Comment by samtstern** [comment]
This will be released soon in `7.3.1`

**Comment by jpreynat** [comment]
Great 👍
Thanks for the explanation on the API update.

**Pull request merged**
