### PR TITLE
Export custom claims

### PR DESCRIPTION
**Pull request by y-a-n-n**
### Description

When exporting and importing users, preserve any custom claims for each user.

### Scenarios Tested

Tested export of users with custom claims, and re-import of exported user file to ensure custom claims are imported to new project successfully.

### Sample Commands
No changes to commands or flags

### CODE REVIEW

**Comment by y-a-n-n** [comment]
@googlebot I signed it!

**Comment by samtstern** [comment]
@y-a-n-n thank you for the contribution!  This seems like a good change to me, but let me find someone from the Firebase Auth team to review it.

**Comment by y-a-n-n** [comment]
Hi! Any progress on this?

**Review by yuchenshi — COMMENTED** [review]
This looks pretty solid to me. Just one last thing: could you please add a test that exports a user with customAttributes to make sure we cover the full round trip?

**Comment by y-a-n-n** [comment]
Thanks, that test has been added now.

**Review by avolkovi — APPROVED** [review]

**Review by yuchenshi — APPROVED** [review]

**Comment by yuchenshi** [comment]
Okay, now please update your branch and resolve the conflicts in `CHANGELOG.md` and you're all set.

**Comment by y-a-n-n** [comment]
Done, thanks!

**Comment by yuchenshi** [comment]
This is now merged and will ship with the next release of Firebase CLI. Thanks again!

**Pull request merged**
