### PR TITLE
Support symbolic links to files and directories

### PR DESCRIPTION
**Pull request by akshetpandey**
### Description
Support using symbolic links to point to functions/hosting folder and other files that the CLI may need.

### Sample Commands
No changes to the CLI

### CODE REVIEW

**Comment by akshetpandey** [comment]
Fixes #586

**Comment by laurenzlong** [comment]
Thanks for the PR! This appears to only fix hosting, since functions source upload does not make use of fsutils. Assigning to @mbleigh to take a further look.

**Comment by laurenzlong** [comment]
It appears like symlinks in functions source directory will be fixed once https://github.com/archiverjs/node-archiver/pull/293 is merged, and we upgrade to a new version of archiver.

**Comment by akshetpandey** [comment]
Strange, we are using my branch of this tool and functions symlink is working fine

**Comment by akshetpandey** [comment]
This code here https://github.com/firebase/firebase-tools/blob/master/lib/deploy/functions/prepare.js#L26 using fsutils fails the check for symlinks when deploying functions that is fixed by this PR

**Comment by laurenzlong** [comment]
Ahh, thanks for pointing that out, I misunderstood, and thought you mean symlinks inside of the source folder, you meant that the whole folder is a symlink. Clever find!

**Comment by psolbach** [comment]
Any news on symlinking to outside of `/functions`? It appears that https://github.com/archiverjs/node-archiver/pull/293 was merged a while ago.

**Comment by laurenzlong** [comment]
@psolbach Yes it was merged, but there was no release cut yet with the newly merged code, so we can't upgrade the dependency. @mbleigh Please take a look at the PR when you get a chance, thanks!

**Comment by akshetpandey** [comment]
We can also go back to 2.0.3 instead of 2.1.0 since that also fixes the problem.

**Comment by akshetpandey** [comment]
2.1.1 was released with the fix included, yay
https://github.com/archiverjs/node-archiver/releases/tag/2.1.1

**Comment by laurenzlong** [comment]
Awesome! Can you also update your PR to include a change to package.json which updates the version requirement for node-archiver to 2.1.1?

**Comment by akshetpandey** [comment]
@laurenzlong : Update PR with archiver updated to 2.1.1

**Pull request merged**
