### PR TITLE
Migrate API call in eventarcTrigger to stop using requests library

### PR DESCRIPTION
**Pull request by huangjeff5**

### CODE REVIEW

**Review by apascal07 — APPROVED** [review]

**Review by bkendall — APPROVED** [review]
I appreciate you.

**Comment by huangjeff5** [comment]
> I appreciate you.

:)

That being said, I had to change our server response to return JSON (previously it accepted strings). Ideally we shouldn't have to do that and the client can just handle the response. Do you happen to know if there's a setting that enables v2 client to handle non-JSON responses?

**Comment by bkendall** [comment]
Yup - you want to use `Client.request` and set all the options yourself. You can then do what you want with the body once you have it (string, xml, binary, gibberish). But since _most_ APIs are JSON based 'round these parts, that's the default we went with.

**Comment by bkendall** [comment]
Link example: https://github.com/firebase/firebase-tools/blob/master/src/test/apiv2.spec.ts#L127-L132

**Pull request merged**
