### PR TITLE
Fix console.log()

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes issue #1817
	 
### Scenarios Tested

Using this function:
```js
exports.helloWorld = functions.https.onRequest(async (req, res) => {
    console.log("log");
    console.log("log", 1, 2);
    console.log("log", [false]);
    console.info("info");
    console.info("info", 1, 2);
    console.info("info", [false]);
    console.warn("warn");
    console.warn("warn", 1, 2);
    console.warn("warn", [false]);
    console.error("error");
    console.error("error", 1, 2);
    console.error("error", [false]);

    res.json({
        hello: 'world',
        date: new Date()
    });
});
```

**Before**
```
i  functions: Beginning execution of "helloWorld"
>  log
>  log 1 2
>  log false
>  info
>  info 1 2
>  info [ false ]
>  warn
>  warn 1 2
>  warn [ false ]
>  error
>  error 1 2
>  error [ false ]
```

**After**
Notice the third line, false is now in an array
```
i  functions: Beginning execution of "helloWorld"
>  log
>  log 1 2
>  log [ false ]
>  info
>  info 1 2
>  info [ false ]
>  warn
>  warn 1 2
>  warn [ false ]
>  error
>  error 1 2
>  error [ false ]
```

### Sample Commands

N/A

### CODE REVIEW

**Comment by samtstern** [comment]
@abeisgoat I can't actually figure out why we needed to override `console.log` in the first place.  I *think* it's because we used to do our communication with the functions emulator through `stdout` but now we use an actual IPC channel so I think `console.log()` can now just fall through to the same place you're handling `console.info` and `console.error`.

**Comment by samtstern** [comment]
Ok I broke the tests since they're all waiting for `USER` logs which don't actually happen.  Were we doing this for observability purposes mainly?

**Comment by abeisgoat** [comment]
Issue makes sense since `.join(' ')` isn't really the exact same thing `console.log()` does to, so thinking back some discrepancy makes sense.

**Comment by samtstern** [comment]
@bkendall sorry in advance I got bit by my least favorite bug here.  If you hit "Enter" on your keyboard when doing Squash and Merge instead of mouse-clicking the button then it lies to you and puts all the commits into `master`.

**Pull request merged**
