### PR TITLE
fix: add codebase config runtime to delegate context object

### LINKED ISSUE #6973: `runtime` field is required but was not found in firebase.json or package.json
### [REQUIRED] Environment info

**firebase-tools:** 13.7.1
**firebase-functions:** 4.9.0
 

**Platform:** macOS, Ubuntu

### [REQUIRED] Test case

- Deploy existing functions after upgrade from 13.6 to 13.7.1

### [REQUIRED] Steps to reproduce

- Deploy functions in a codebase

```
{
	"functions": [
		{
			"source": "api/career-functions",
			"codebase": "career-functions",
			"runtime": "nodejs18"
		},
}
```

- engines field in package.json 

```
"engines": {
		"node": "18",
		"pnpm": ">=8"
	},
```

### [REQUIRED] Expected behavior

- Deployment is successfully as usual 

### [REQUIRED] Actual behavior

image

### PR DESCRIPTION
**Pull request by luc-mo**
### Description
Recently, I encountered an issue that arose unexpectedly during the deployment of firebase functions. The error occurs due the `runtime` field is not recognized in the `firebase.json` file, thereby causing a failure in the deployment.

Fixes #6973 

Deployment log:
```
i  deploying  functions
i  functions: preparing  codebase  default  for  deployment
i  functions: ensuring  required  API  cloudfunctions.googleapis.com  is  enabled...
i  functions: ensuring  required  API  cloudbuild.googleapis.com  is  enabled...
i  artifactregistry: ensuring  required  API  artifactregistry.googleapis.com  is  enabled...
✔ functions: required  API  cloudbuild.googleapis.com  is  enabled
✔ functions: required  API  cloudfunctions.googleapis.com  is  enabled
✔ artifactregistry: required  API  artifactregistry.googleapis.com  is  enabled

Error: `runtime`  field  is  required  but  was  not  found  in  firebase.json  or  package.json.
To  fix  this, add  the  following  lines  to  the  `functions`  section  of  your  firebase.json:
"runtime": "nodejs20"  or  set  the  "engine"  field  in  package.json
Cleaning  up  project  directory  and  file  based  variables00:01
ERROR: Job  failed: exit  code  1
```

### Scenarios Tested
I conducted tests by installing other versions of the package and attempting to deploy, coming to the conclusion that it was an error introduced in version *13.6.1* where the `runtime` property was removed from the `delegateContext` object declaration. The error does not occur in versions previous to *13.6.1*.

I performed the test by doing an `npm link` of firebase-tools package and deploying my functions manually. These were deployed successfully.

Deployment log with changes:
```
i  functions: Loaded environment variables from .env.
i  functions: preparing . directory for uploading...
+  functions: . folder uploaded successfully
i  functions: updating Node.js 20 (1st Gen) function health(us-central1)...
i  functions: updating Node.js 20 (1st Gen) function users(us-central1)...

+  functions[health(us-central1)] Successful update operation.
+  functions[users(us-central1)] Successful update operation.

i  functions: cleaning up build files...
+  Deploy complete!
```

### CODE REVIEW

**Comment by inlined** [comment]
Looks good to me. Can you add a line to CHANGELOG.md saying:

"Fixes bug detecting functions runtime from firebase.json (#6964)"?

**Comment by luc-mo** [comment]
Added! 😄

**Comment by colerogers** [comment]
@luc-mo It looks like the linter failed, could you run `npm run format` to fix the issue? I think it's probably just complaining about a newline at the end of the changelog

**Comment by luc-mo** [comment]
Fixed 😄

**Review by inlined — APPROVED** [review]

**Pull request merged**
