### PR TITLE
fix: peerDep warning of marked dep

### PR DESCRIPTION
**Pull request by AviVahl**
### Description

upgrade marked-terminal to its new version, which re-introduces cjs support and is compatible with the used marked v4

see https://github.com/mikaelbr/marked-terminal/issues/97

### Scenarios Tested

`npm test` passes.

### CODE REVIEW

**Comment by AviVahl** [comment]
Ah, one of them deps uses `node:process` (and others), which isn't supported on Node 12.
Considering Node 12 is EOL soon, would you consider accepting a PR making firebase-tools Node 14+?

**Comment by bkendall** [comment]
> Ah, one of them deps uses `node:process` (and others), which isn't supported on Node 12.

This is a bummer... 

> Considering Node 12 is EOL soon, would you consider accepting a PR making firebase-tools Node 14+?

Not yet. It's still got until April...

(This is rather a difficult thing to balance between CF3/GCF priorities and supported Node versions and keeping the CLI relatively up to date. I'm working to try to keep the difference a little tighter - we only dropped Node 10 in December - so hopefully the answer to that becomes "yes" relatively soon.)

(Oh hey, if you're interested in infrastructural changes though, we're working to make sure [the entire codebase in Typescript](https://github.com/firebase/firebase-tools/milestone/3) and then I'm going to look at what it would take to get the repo to a point, probably in Node 14 land, where it itself is either ESM-based or doesn't completely bulk at ESM dependencies. Always happy for more help on that front - see the milestone for the list of remaining files 😄 )

I'm going to close this for now since it's not gonna be possible to merge... for a bit.

**Comment by AviVahl** [comment]
Thank you for reviewing this and the reasoning. Much appreciated.

I'll see if I can find the time/capacity to contribute further, even though I'm less familiar with the inner workings of this library. 😅

**Comment by AviVahl** [comment]
heya @bkendall
Node 12 is now EOL... are you guys planning to drop it? (should I open a new PR with this change?)

**Comment by bkendall** [comment]
It's coming! We've got the `next` branch with some node related changes lined up, including fixing this marked issue :) Coming... soon.

**Pull request closed without merging**
