### PR TITLE
Pass down functions.ignore values in firebase.json to functions emulator

### PR DESCRIPTION
**Pull request by dikatok**
Pass down `functions.ignore` values in `firebase.json` to functions emulator so that supposedly ignored directories/files will not trigger reload.

### CODE REVIEW

**Comment by dikatok** [comment]
Whoops, apparently I forgot to checkout my new branch and committed the changes to the master branch of my fork, is that okay?

**Review by joehan — APPROVED** [review]
Thanks for the contribution! Lgtm, but could you add an entry to changelog.md for this change?

**Comment by dikatok** [comment]
@joehan do you mean `changelog.md` in the root directory? is it supposed to be empty?

**Comment by dikatok** [comment]
fixes #2131

**Pull request merged**
