### PR TITLE
fix: handle paths with spaces in getGlobalEsbuildVersion function

### PR DESCRIPTION
**Pull request by dxdc**
### Description

- Wrapped the binPath in double quotes to correctly handle paths containing spaces.
- Ensured execSync properly executes the command when the binary path includes spaces.

### CODE REVIEW

**Review by joehan — APPROVED** [review]

**Comment by joehan** [comment]
Looks like there are test failures for this, please fix.

**Comment by dxdc** [comment]
done

**Comment by jamesdaniels** [comment]
@leoortizz PTAL

**Review by chalosalvador — APPROVED** [review]
LGTM!

**Pull request merged**
