### PR TITLE
refactor: migrate from cli-color to colorette

### LINKED ISSUE #4793: firebase-tools depends es5-ext (via cli-color), which prints messages when in Russia
(am I making a mistake by opening this Pandora box?)

### [REQUIRED] Environment info

**firebase-tools:** 11.4.0

**Platform:** Fedora 36

### [REQUIRED] Test case

This is happening upon installation.

### [REQUIRED] Steps to reproduce

(when in russia)
```sh
mkdir fb-postinstall
cd fb-postinstall
npm init -y
npm i firebase firebase-tools
```

### [REQUIRED] Expected behavior

Installation without additional unrelated messages.

### [REQUIRED] Actual behavior

`es5-ext/_postinstall.js` has the following code:
```js
#!/usr/bin/env node

// Broadcasts "Call for peace" message when package is installed in Russia, otherwise no-op

"use strict";

try {
	if (
		[
			"Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka",
			"Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk",
			"Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Tomsk",
			"Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg",
			"Europe/Astrakhan", "Europe/Kaliningrad", "Europe/Kirov", "Europe/Moscow",
			"Europe/Samara", "Europe/Saratov", "Europe/Simferopol", "Europe/Ulyanovsk",
			"Europe/Volgograd", "W-SU"
		].indexOf(new Intl.DateTimeFormat().resolvedOptions().timeZone) === -1
	) {
		return;
	}

	var bold = function (msg) { return "\x1b[97m\x1b[1m" + msg + "\x1b[22m\x1b[37m"; };

	var flags = function () {
		return (
			"🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦" +
			"  🇷🇺  🇺🇦  🇷🇺  🇺🇦  🇷🇺  🇺🇦"
		);
	};

	process._rawDebug(
		[
			"", flags(), "",
			"\x1b[37m24 февраля " +
				bold("Россия напала на Украину") +
				", что уже стало причиной " +
				bold("7000+ жертв среди российских военных") +
				" и примерно " +
				bold("2000-4000 - среди украинских") +
				", а также " +
				bold("780 убитых граждан, в том числе 36 детей") +
				".",
			"",
			"Народ Украины всеобще мобилизован и готов защищать свою страну от вражеского" +
				" вторжения. " +
				bold(
					"91% украинцев полностью поддерживает своего президента Владимира Зеленского"
				) +
				" и его ответные действия на нападение России.",
			"",
			"Весь мир осудил необоснованное вторжение и решил ввести " +
				bold("невиданные ранее санкции против России") +
				". С каждым новым днем они будут ощущаться все сильнее и сильнее среди мирных" +
				" граждан.",
			"",
			"В то же время, " +
				bold("российское правительство ограничивает доступ граждан к внешней информации") +
				", насаждая однобокие формулировки и версии происходящего.",
			"", "В качестве надежного источника информации загрузите безопасный браузер Tor:", "",
			bold(
				"https://forum.torproject.net/t/tor-blocked-in-russia-how-to-circumvent-censorship/982"
			),
			"", "И посетите:", "",
			bold(
				"https://www.bbcweb3hytmzhn5d532owbu6oqadra5z3ar726vq5kgwwn6aucdccrad.onion/russian"
			),
			"", flags(), "",
			bold("Прекратите эту бессмысленную войну! Остановите военного преступника Путина!") +
				"\x1b[39m",
			"", flags(), ""
		].join("\n")
	);
} catch (error) {
	// ignore
}
```

Related:
https://github.com/microsoft/TypeScript/pull/50061

### Side note

I personally hope Russian aggression and the war in Ukraine will end. I hope less lives will be lost. I hope for lasting peace.

### PR DESCRIPTION
**Pull request by AviVahl**
### Description

migrate codebase from `cli-color` to `colorette`
fixes #4793

### CODE REVIEW

**Comment by AviVahl** [comment]
@bkendall there are 6 type errors left. all around strip and move.

**Comment by AviVahl** [comment]
I've rebased to include latest commits from `master`

**Comment by bkendall** [comment]
True to my word I think I have the last 5%. I'm going to run this through a couple paces and somehow get the commit to you

**Comment by bkendall** [comment]
I _think_ what you can do is this. Fetch the references in firebase/firebase-tools, and then cherry-pick this commit:

`git cherry-pick 4f957f49b`

If that doesn't work, I'll make a new PR from the `cli-color-to-colorette` which includes both commits.

**Comment by AviVahl** [comment]
Used the GitHub UI to sync the fork :+1: it actually works pretty well when there are no conflicts

**Comment by bkendall** [comment]
Could you do one last thing: add a small entry to `CHANGELOG.md` that reads something like

```markdown
- Replaces underlying terminal coloring library.
```

**Comment by AviVahl** [comment]
done

**Review by bkendall — APPROVED** [review]

**Pull request merged**
