### PR TITLE
Documentation for firestore.indexes.json format

### PR DESCRIPTION
**Pull request by markarndt**
Juan gave me comments already.

Please modify reviewer list as needed.

Lots of blank commits here, sorry if I missed a squash and merge option somewhere.

### CODE REVIEW

**Comment by samtstern** [comment]
@bkendall I believe Mark's plan is to copybara it in to the official docs.

**Comment by markarndt** [comment]
> I'm curious why this content is being put in `src/firestore/README.md`. Documentation that deep into the code base isn't going to be easy to discover.
> 
> 1. Should this live in the [official Firebase docs](https://firebase.google.com/docs/cli)?
> 2. If not, could it live directly in the top-level `README.md`?

Yeah, this file will get fetched and munged into something publishable on Firesite. I'd like the doc source to live near the code, in the off chance that someone coming in to change the index file format will see that there are doc impacts. In an ideal world, this content would have been in docstrings inside the source flles, but running typedoc on a handful of files doesn't generate anything all that useful, so README was next best thing.

No {include} directive type thingy in GitHub, otherwise I'd change to top-level README to point to this.

Can we live with this imperfect solution?

**Comment by samtstern** [comment]
@markarndt I have no objections to this solution for now.  I think we can improve it over time, possibly by creating type definition files for the various Firebase CLI JSON files and using the same pipeline that we use for Rules to generate some reference docs in addition to this guide.

**Comment by markarndt** [comment]
+1!

**Comment by markarndt** [comment]
@samtstern 
Are you OK with the content of this? While we're discussing mechanics, what lives where, etc,  I could get this published...

**Comment by samtstern** [comment]
@markarndt thanks for the reminder.  Approved.

**Comment by samtstern** [comment]
@markarndt looks like the linter doesn't like the MD.  Could you run `npm run format` and see if it fixes it?

**Pull request merged**
