### PR TITLE
Command Line Tool to import CSV and JSON files into Cloud Firestore easily

### PR DESCRIPTION
**Pull request by allusai**
### Description

Currently the most popular way to import data from a CSV or JSON file to your Cloud Firestore database is manually. I followed the steps outlined by Devesu in this Medium article (https://medium.com/@devesu/how-to-upload-data-to-firebase-firestore-cloud-database-63543d7b34c5). It was very tedious and error-prone for me to follow each step manually to import my data. This process is especially intimidating for beginner programmers, it creates a barrier to entry and makes a less user-friendly experience for Firebase customers. There are other npm packages that are out there for importing data, but all of them require manually inserting code snippets or copy-pasting scripts locally.

I wanted there to just be a command line tool built into Firebase which doesn't require much work. I just want to run one command and have the CSV or JSON data imported. That's why I created this new feature called "firestore-upload" to do just that.

I used the original source code from Devesu in this tool and also other Internet sources. I just want to give proper credit to them here by showing my citations. I also commented in my files exactly which code I referenced from who. 

Citations:
1) Devesu: https://medium.com/@devesu/how-to-upload-data-to-firebase-firestore-cloud-database-63543d7b34c5
2) Dennis: https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/21128172
3) Google Bash Style Guide
4) Petesh and Ludovic: https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash

### Scenarios Tested

List of user journeys and edge cases tested

- Upload a valid CSV file to an existing Firestore DB collection and see the data show up on the Firebase console
- Upload a valid JSON file to an existing Firestore DB collection and see the data show up on the Firebase console
- Upload a valid CSV file to a new Firestore DB collection (not already in the DB)
- Upload a valid JSON file to a new Firestore DB collection (not already in the DB)
- Upload a badly formatted CSV file and get an error message
- Upload a badly formatted JSON file and get an error message
- File path of the CSV/JSON file is invalid/not found
- Attempt to upload a directory instead of a CSV or JSON file
- Attempt to upload a file with an extension other than ".csv" or ".json"
- Attempt to upload to an invalid database url
- Attempt to upload a file with "dockeys" (see https://medium.com/@devesu/how-to-upload-data-to-firebase-firestore-cloud-database-63543d7b34c5)
- Attempt to upload a file without "dockeys" and request them to be auto-generated (see above link)

### Sample Commands

Since I am not familiar with the architecture of this project, I haven't "integrated" my firestore-upload tool with the rest of the project. I know eventually the files might be placed in a more appropriate directory and the name of the tool might be renamed to match the style of the rest of the project. There might also be broader changes to the design of the tool such as the way that flags are used in the command.

For right now though, I created a demo showing how to use this tool. I attached a zip file below called "firestore-upload-demo.zip". These are the steps on how to run the demo

1) Download the zip file and open it to get a folder called "firestore-upload-demo". This contains the command line tool and some sample data files for demo purposes.

2) Create a Cloud Firestore database for testing. Download the service account private key JSON file into the "firestore-upload-demo" folder. Also, write down the database URL mentioned on the page where you download the private key. See Devesu's Medium article from before for more details.

3) Now, open the Terminal/Command Line and cd to the firestore-upload-demo directory. Run "npm install" to install the node_modules needed by the tool.

4) Lastly, run the following command to upload a sample CSV file to your Cloud Firestore database. Make sure to fill in the values for your private key file path and database URL from earlier before you run the command.
`sh firestore-upload.sh -f data.json -k firebase_service_account_private_key_json_file_path -d firestore_db_url -c newTestCollection -y`

5) You can also run this command to upload a sample JSON file. Just make sure to delete the documents that were created in Step 4, otherwise, Firebase will see these as duplicate documents and not add them to the DB. Again, make sure to fill in the values for your private key file path and database URL from earlier before you run the command.
`sh firestore-upload.sh -f test.csv -k firebase_service_account_private_key_json_file_path -d firestore_db_url -c newTestCollection -y`

[firestore-upload-demo.zip](https://github.com/firebase/firebase-tools/files/5644103/firestore-upload-demo.zip)

### CODE REVIEW

**Comment by expelledboy** [comment]
I am not associated with the project, but I was looking to see if this included this functionality and found your PR.

Following the cli execution path for firestore delete
- https://github.com/firebase/firebase-tools/blob/master/src/bin/firebase.js
- https://github.com/firebase/firebase-tools/blob/master/src/index.js
- https://github.com/firebase/firebase-tools/blob/master/src/commands/firestore-delete.ts

That should give you and idea of how to integrate with the project structure. Cheers

**Comment by allusai** [comment]
Thank you!

**Comment by samtstern** [comment]
@allusai thanks for starting this discussion and for creating such a detailed description of what you are trying to do!  We've already considered adding this type of functionality to the Firebase CLI in the past, but we decided against it.  Firestore does not have an official JSON or CSV export format and we're not going to create one at this time.  Firestore *does* have a [binary import/export format](https://firebase.google.com/docs/firestore/manage-data/export-import) and we support this in both the emulators and in production.

However we do understand that for some developers with small/simple data sets a CSV or JSON export solution can be useful.  If you'd like to share your solution we have two venues which are more appropriate than the CLI:

- https://firebaseopensource.com/ - if you want to put your scripts into a GitHub repo I'd be happy to list them here.  There are already a few similar projects
- https://medium.com/firebase-developers - if you want to convert your advice into a blog post you could submit it to our Medium channel

I'm going to close this PR since we're not going to add this to the CLI directly, I hope you understand!  Feel free to add more comments below.

**Comment by expelledboy** [comment]
@samtstern you support binary import export to production?

I dont necessarily want JSON, many projects I imagine are just looking to be able to download or upload data used during testing.

**Comment by allusai** [comment]
Thank you for the feedback samtstern, I will look into it!

**Comment by samtstern** [comment]
@expelledboy yes please see https://firebase.google.com/docs/firestore/manage-data/export-import

**Comment by expelledboy** [comment]
Thanks. That solution requires Cloud Storage, something I wouldn't necessarily want to enable for every project. But I am still a newbie firebase user 👍

**Comment by samtstern** [comment]
@expelledboy yes in production Firestore can only export/import through Cloud Storage.  The nice thing about that is that it's a fully managed operation, it doesn't use your local disk or network.

**Pull request closed without merging**
