### PR TITLE
Fix database:remove command

### PR DESCRIPTION
**Pull request by sarajmunjal**
### Description
Fix `database:remove` command b/169565783
### Scenarios Tested
```
firebase database:remove /somePath --instance <instance> --project <project>
```

### CODE REVIEW

**Review by yuchenshi — APPROVED** [review]
YOLO

**Comment by pfinazzo** [comment]
Hi there I noticed this was merged yesterday! I am running into this issue right now, and was wondering when this fix will be deployed to npm so I can update it! Need this command to delete some large refs on our db. Thanks! 👍

**Comment by pfinazzo** [comment]
actually nevermind I will use `--data null` on set command for now. Thanks though!

**Comment by pfinazzo** [comment]
ah actually nevermind again, I do still need this updated, I just installed the latest binary and issue is still happening for me :/ problem is I cant use database:set because of the size limit

**Pull request merged**
