### PR TITLE
Remove tools:migrate command and identifierToProjectId method

### PR DESCRIPTION
**Pull request by TrCaM**
### Description

- Deprecate and remove the outdated `tools:migrate` command.
- Remove `identifierToProjectId.js` and its usages in `tools-migrate.js` and `requireAccess.ts`

### CODE REVIEW

**Comment by TrCaM** [comment]
> Does this not work today?

@mbleigh said to me that I this command isn't relevant anymore and we can safely remove it

**Comment by TrCaM** [comment]
Hey @bkendall, can I get your feedback on this PR as well?

**Comment by bkendall** [comment]
So before we full-on remove this, we want to have a deprecation period where it prints a warning that the command will be removed. Do you want to make a PR that does so? Once that goes in, then we can merge this when we want to fully remove it.

**Comment by TrCaM** [comment]
Sure, I'll make another PR for this

**Pull request closed without merging**
