### PR TITLE
Allow skipping informational IAM check via env.

### LINKED ISSUE #2083: firestore.delete hitting Cloud Resource Manager API. Exceeding quota limit. Does not report in  console quota reports.
### [REQUIRED] Environment info

**firebase-tools:**
"firebase-tools": "7.6.0",

**Platform:**
Google Cloud Functions

### [REQUIRED] Test case
Call delete more then 1000 times under 100 seconds using the method described in 
https://firebase.google.com/docs/firestore/solutions/delete-collections.

Snippet of what is called.
```
  // Now clean up the batches node
    const batchPath = processRef.collection('batches').path;
    await firebase_tools.firestore
        .delete(batchPath, {
          project: process.env.GCLOUD_PROJECT,
          recursive: true,
          yes: true,
          token: env.fb.token
        });
```

You will get the following API error.
crm-quota3

### [REQUIRED] Steps to reproduce
Call firebase_tools.firestore.delete more then 1000 times in 100 seconds.  
Our use case:  We are using firestore for batch orchestration which leads to lots of document deletes. 

### [REQUIRED] Expected behavior
We were a bit blindsided by the API quota.  If you need to delete collections at a massive scale this is a solid limitation.  Though disappointed I'm not going to call this a bug (though is should be documented). The actual issue is that even though we are getting failure due to the API limit, this is not being reported in the console project.

### [REQUIRED] Actual behavior
I would expect the quota usage to be reported in the cloud console project. As of right now it is not,
crm-quota
crm-quota2

With this data populated it would help us work with our case manager to get quota increase and allow us to set monitors on its consumption rate.

### PR DESCRIPTION
**Pull request by mbleigh**
Fixes #2083 -- this allows an escape hatch for users who are running into issues with the informational `testIamPermissions` checks that are run before (nearly) every command. By setting the `FIREBASE_SKIP_INFORMATIONAL_IAM` (intentionally long and cumbersome) environment variable, the method will return early thus avoiding the API call.

### CODE REVIEW

**Comment by samtstern** [comment]
Oh nice!  This will also help @maierson in https://github.com/firebase/firebase-tools/issues/2059#issuecomment-606199687

**Comment by mbleigh** [comment]
A question for @samtstern and @bkendall -- in addition to this change, I was contemplating automatically skipping the informational checks when being used as a package as opposed to a CLI...thoughts?

**Comment by samtstern** [comment]
@mbleigh that would be a good idea, can you show me what the failure case would look like if you skip the informational checks when using it as a package but don't actually have the right IAM roles?

**Comment by mbleigh** [comment]
@samtstern no, that's why the checks are there in the first place -- the errors may manifest in a bunch of different less helpful ways since any of the random API calls the CLI makes might fail. Some might be perfectly reasonable, others totally opaque.

**Comment by samtstern** [comment]
@mbleigh ok that's fair ... but I wonder if we should make this opt-in then?  Especially since I imagine this could become popular within Extensions and they have very specific IAM.  With `requireAuth` you avoid certain classes of bugs where some parts of the invocation succeed and others fail.  If we let auth fall through then we don't actually know what the behavior would be.

**Comment by mbleigh** [comment]
Then let's just leave it as an env escape hatch for now, and we can take another look if it seems like we oughta.

**Pull request merged**
